//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="MDIMenu.Properties.Resources.get_ResourceManager():System.Resources.ResourceManag" +
    "er")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="MDIMenu.Properties.Resources.get_Culture():System.Globalization.CultureInfo")]
[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="MDIMenu.Properties.Resources.set_Culture(System.Globalization.CultureInfo):Void")]

namespace MDIMenu.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDIMenu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Flag_blue {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Flag_blue", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_green {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Flag_green", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_red {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Flag_red", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap NewWindow {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("NewWindow", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Save", resourceCulture)));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Stop", resourceCulture)));
            }
        }
    }
}
